[phases.setup]
aptPkgs = [
  "chromium",
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "expat",
  "fontconfig",
  "freetype",
  "gdk-pixbuf",
  "gtk3",
  "libX11",
  "libXcomposite",
  "libXcursor",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXrandr",
  "libxkbcommon",
  "pango",
  "alsa-lib"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"